defaults:
  - _self_
  - model: t5base
dry_run: False
wandb:
  project: "glue_new"
  name: null
  entity: "yuanhezhang6-university-of-warwick"
hydra:
  sweeper:
    params:
      ++dataset_name: mnli
      ++seed: 0
